pool:
  vmImage: 'ubuntu-18.04'

trigger:
  batch: true
  branches:
    include:
      - master

jobs:
  - job: ValidationCheck
    steps:
    - task: JavaToolInstaller@0
      inputs:
        versionSpec: '8'

    - task: UsePythonVersion@0
      displayName: 'Select Python Version 3.6'
      inputs:
        versionSpec: '3.6'
        architecture: 'x64'

    - script: python -m pip install --upgrade pip setuptools wheel
      displayName: 'Install and Upgrade Pip'

    - script: pip install -r requirements.txt
      displayName: 'Install Python Requirements'

    - script: html5validator --skip-non-svg --root ./
      displayName: 'Validate Vectors'
